package com.netflix.artemis.plugins.karyon;

import com.google.inject.Inject;
import com.netflix.artemis.PluginService;
import io.reactivex.netty.protocol.http.server.HttpServer;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dchoudhury' at '8/29/14 1:42 AM' with Gradle 1.12
 *
 * @author dchoudhury, @date 8/29/14 1:42 AM
 */
public class KaryonService implements PluginService {

    private HttpServer httpServer;

    public boolean someLibraryMethod() {
        return true;
    }

    @Inject
    public KaryonService(HttpServer httpServer) {
        this.httpServer = httpServer;
    }

    @Override
    public void start() throws Exception {
        new Runnable() {
            @Override
            public void run() {
                httpServer.startAndWait();
            }
        }.run();
    }

    @Override
    public void stop() throws Exception {
        httpServer.shutdown();
    }

    @Override
    public String name() {
        return "KaryonPlugin";
    }
}
