import com.netflix.artemis.plugins.karyon.KaryonService;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'dchoudhury' at '8/29/14 1:42 AM' with Gradle 1.12
 *
 * @author dchoudhury, @date 8/29/14 1:42 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}
